"""
NetStealth Log Validation Utility

Validates NetStealth log completeness and quality with clear user feedback.
"""

from pathlib import Path
from typing import Dict, List, Tuple
from dataclasses import dataclass
from enum import Enum
import json

class LogStatus(Enum):
    """Status of a log file."""
    COMPLETE = "complete"
    INCOMPLETE = "incomplete"
    MISSING = "missing"
    CORRUPTED = "corrupted"

@dataclass
class LogValidationResult:
    """Results of log file validation."""
    log_type: str
    status: LogStatus
    file_path: Path
    file_size: int
    issues: List[str]
    impact: str

class NetStealthLogValidator:
    """Validates logs generated by NetStealth."""
    
    EXPECTED_LOGS = {
        "poc_execution": {
            "filename": "poc_execution.log",
            "min_size": 500,
            "required_patterns": ["INFO", "session", "Authentication successful"],
            "impact": "Cannot analyze workflow execution patterns"
        },
        "browser_console": {
            "filename": "browser_console.log", 
            "min_size": 50,
            "required_patterns": ["Page loaded", "DOM ready"],
            "impact": "Cannot detect JavaScript errors or browser issues"
        },
        "network_trace": {
            "filename": "network_trace.har",
            "min_size": 1000,
            "required_patterns": ['"log"', '"entries"', '"pages"'],
            "impact": "Cannot analyze network requests and timing"
        },
        "mitmproxy": {
            "filename": "mitmproxy_session.log",
            "min_size": 50, 
            "required_patterns": ["GET", "200 OK"],
            "impact": "Cannot analyze proxy configurations"
        }
    }
    
    def validate_netstealth_logs(self, logs_dir: Path) -> Dict[str, LogValidationResult]:
        """Validate all expected NetStealth log files."""
        results = {}
        
        for log_type, config in self.EXPECTED_LOGS.items():
            log_file = logs_dir / config["filename"]
            results[log_type] = self._validate_single_log(log_type, log_file, config)
        
        return results
    
    def _validate_single_log(self, log_type: str, log_file: Path, config: Dict) -> LogValidationResult:
        """Validate a single log file."""
        issues = []
        
        if not log_file.exists():
            return LogValidationResult(
                log_type=log_type,
                status=LogStatus.MISSING,
                file_path=log_file,
                file_size=0,
                issues=["Log file was not generated"],
                impact=config["impact"]
            )
        
        file_size = log_file.stat().st_size
        
        # Check if file is empty or too small
        if file_size == 0:
            issues.append("Log file is empty - generation failed")
            status = LogStatus.CORRUPTED
        elif file_size < config["min_size"]:
            issues.append(f"Log file unusually small ({file_size} bytes, expected >{config['min_size']})")
            status = LogStatus.INCOMPLETE
        else:
            # Check content patterns for non-empty files
            try:
                content = log_file.read_text(encoding="utf-8")
                
                # For HAR files, validate JSON structure
                if log_type == "network_trace":
                    try:
                        json.loads(content)
                    except json.JSONDecodeError as e:
                        issues.append(f"Invalid HAR JSON format: {e}")
                        status = LogStatus.CORRUPTED
                        return LogValidationResult(log_type, status, log_file, file_size, issues, config["impact"])
                
                # Check for required patterns
                missing_patterns = []
                for pattern in config["required_patterns"]:
                    if pattern not in content:
                        missing_patterns.append(pattern)
                
                if missing_patterns:
                    issues.append(f"Missing expected content: {missing_patterns}")
                    status = LogStatus.INCOMPLETE
                else:
                    status = LogStatus.COMPLETE
                    
            except Exception as e:
                issues.append(f"Cannot read log file: {e}")
                status = LogStatus.CORRUPTED
        
        return LogValidationResult(
            log_type=log_type,
            status=status,
            file_path=log_file,
            file_size=file_size,
            issues=issues,
            impact=config["impact"]
        )
    
    def generate_validation_report(self, results: Dict[str, LogValidationResult]) -> str:
        """Generate human-readable validation report."""
        report_lines = [
            "🔍 NetStealth Log Validation Report",
            "=" * 50,
            ""
        ]
        
        # Summary
        complete_count = sum(1 for r in results.values() if r.status == LogStatus.COMPLETE)
        incomplete_count = sum(1 for r in results.values() if r.status == LogStatus.INCOMPLETE)
        missing_count = sum(1 for r in results.values() if r.status == LogStatus.MISSING)
        corrupted_count = sum(1 for r in results.values() if r.status == LogStatus.CORRUPTED)
        total_count = len(results)
        
        report_lines.extend([
            f"📊 SUMMARY: {complete_count}/{total_count} logs complete",
            f"   • Complete: {complete_count}",
            f"   • Incomplete: {incomplete_count}",  
            f"   • Missing: {missing_count}",
            f"   • Corrupted: {corrupted_count}",
            ""
        ])
        
        # Analysis readiness
        if complete_count == total_count:
            report_lines.append("✅ READY FOR FULL ANALYSIS")
        elif complete_count >= 2:
            report_lines.append("⚠️  PARTIAL ANALYSIS POSSIBLE - Some features limited")
        else:
            report_lines.append("❌ INSUFFICIENT DATA - Analysis severely limited")
        
        report_lines.append("")
        
        # Detailed log status
        status_icons = {
            LogStatus.COMPLETE: "✅",
            LogStatus.INCOMPLETE: "⚠️", 
            LogStatus.MISSING: "❌",
            LogStatus.CORRUPTED: "🚫"
        }
        
        for log_type, result in results.items():
            icon = status_icons[result.status]
            report_lines.extend([
                f"{icon} {log_type.upper().replace('_', ' ')}: {result.status.value}",
                f"   File: {result.file_path}",
                f"   Size: {result.file_size} bytes"
            ])
            
            if result.issues:
                report_lines.append("   Issues:")
                for issue in result.issues:
                    report_lines.append(f"     • {issue}")
            
            if result.status != LogStatus.COMPLETE:
                report_lines.append(f"   Impact: {result.impact}")
            
            report_lines.append("")
        
        return "\n".join(report_lines)
    
    def get_analysis_readiness(self, results: Dict[str, LogValidationResult]) -> Tuple[str, float]:
        """Get analysis readiness level and confidence score."""
        complete_count = sum(1 for r in results.values() if r.status == LogStatus.COMPLETE)
        total_count = len(results)
        confidence = complete_count / total_count
        
        if confidence >= 1.0:
            readiness = "FULL"
        elif confidence >= 0.5:
            readiness = "PARTIAL"  
        else:
            readiness = "LIMITED"
        
        return readiness, confidence
    
    def get_critical_issues(self, results: Dict[str, LogValidationResult]) -> List[str]:
        """Get list of critical issues that prevent analysis."""
        critical_issues = []
        
        for log_type, result in results.items():
            if result.status in [LogStatus.MISSING, LogStatus.CORRUPTED]:
                critical_issues.append(f"{log_type}: {result.impact}")
        
        return critical_issues
